baseURL = 'http://example.org/'
languageCode = 'bg'
defaultContentLanguage = 'bg'
[languages]
  [languages.bg]
    languageName = "Български"
    title = 'Данни за добро - България'
    copyright = 'Всичко в сайта e под лиценз'
    weight = 1
  [languages.en]
    languageName = "English"
    title = 'Data for good - Bulgaria'
    copyright = 'The content of the web site is published under'
    weight = 2
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"