basic_settings:
  site_title: Data for Good
  favicon_image: /assets/img/favicon.png

header_settings:
  logo_image: /assets/img/brand/white.png
  mobile_logo_image: /assets/img/brand/blue.png
  # Choose a color for your header [blue, dark, light].
  theme: dark
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: home
      urls:
        bg: /
        en: /index-en
    - title: blog
      urls:
        bg: /blog-bg
        en: /blog-en
    - title: contact
      urls:
        bg: /contact-bg
        en: /contact-en

footer_settings:
  footer_tagline: Data for Good Bulgaria

contact_settings:
  form_action: 'https://formspree.io/hello@jekyllthemes.io'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/dataforgoodbg'
  twitter_url: 'https://twitter.com/dataforgoodbg'
  instagram_url: ''
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: 'https://github.com/data-for-good-bg'
  reddit_url: ''
  linkedin_url: 'https://www.linkedin.com/company/data-for-good-bg'

authors:
  tom:
    name: Tom
    picture: /assets/img/faces/team-1.jpg
  jane:
    name: Jane
    picture: /assets/img/faces/team-4.jpg
  michael:
    name: Michael
    picture: /assets/img/faces/michael.jpg

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 